### ISSUE TITLE
DataSource.NotFound / Timestamp

### ISSUE THREAD

**Issue by 20113hz** [xcellr8or/PowerBI-GoogleTimeline#1]
Hi xcellr8or,

Not sure if you're still working on this, but FYI if you are.

Followed the read me and got this error -

"DataSource.NotFound: File or Folder: We couldn't find the folder 'C:\Users\Karen.Stewart\Documents\Downloads\end june 2021\*'.
Details:
    C:\Users\Karen.Stewart\Documents\Downloads\end june 2021"

Solved that one by changing the source but then there is an issue that I've seen reported on the timestamp format having been changed since the publish of this.

"Expression.Error: We cannot convert the value null to type Number.
Details:
    Value=
    Type=[Type]"

Can't fix that as it's beyond me - if you have any thoughts?

**Comment by xcellr8or** [comment]
Hi,

I haven't looked at this in a while but will have a squizz next week. I
have a feeling the format fro  google  changed ... if I can't fix will pull
it down so as not to frustrate more ppl!

**Comment by xcellr8or** [comment]
Hi 20113hz,

I believe I have corrected the problem. As you indicated (thx btw - you saved me some time there!), the json files now include the timestamps in UTC format and I have published a new version of the pbix file. 

I also fixed the file location reference in the helper query. 

Have a go and let me know if this fixes for you.

Thanks,
xcellr8or

**Comment by 20113hz** [comment]
Resolved! Thank you for taking your time to fix it.
